# Generated by Django 3.1.7 on 2021-04-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField(blank=True, default=None, null=True, verbose_name='Weight of food in grams')),
                ('allergens', models.TextField(blank=True, default=None, null=True, verbose_name='List of integers separated by comma')),
                ('ingredients', models.TextField(blank=True, default=None, null=True)),
                ('category', models.CharField(choices=[('SO', 'Soup'), ('OT', 'Other'), ('PI', 'Pizza'), ('SA', 'Salad'), ('FJ', 'Fresh juice'), ('DR', 'Drinks'), ('WI', 'Wine')], default='OT', max_length=2)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='core/static/media/upload')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price in EUR')),
            ],
        ),
    ]
